### ISSUE TITLE
Setting scale direction to COUNTER_CLOCKWISE in GAUGE will display the scale rotated by ~80º

### ISSUE THREAD

**Issue by claudio-rosati** [HanSolo/Medusa#101]
CLOCKWISE
![clockwise](https://cloud.githubusercontent.com/assets/10833922/23358926/20860896-fce4-11e6-92bf-40f0e4742655.png)

COUNTER_CLOCKWISE
![counter_clockwise](https://cloud.githubusercontent.com/assets/10833922/23358937/2e63dea2-fce4-11e6-9393-b8792f849d36.png)

**Comment by HanSolo** [comment]
The reason is that the start angle can be defined by the user. Means if you set the start angle to 320 degrees (default) it will start from the bottom counting ccw up to 320 degree and start from there to draw the tickmarks cw. If you change the scale direction it will also start from 320 degree start angle but in the opposite direction. Not sure if I would like to have that automatic, maybe the user should be responsible to adjust the start angle if it is really needed to change the scale direction at runtime...

**Comment by claudio-rosati** [comment]
Now I understand, thank you.
My users can set the scale direction but not the start ancle, so I can do it depending on the chosen direction.
