### ISSUE TITLE
SetAveragingPeriod not working for SPARK_LINE

### ISSUE THREAD

**Issue by KingGax** [HanSolo/Medusa#186]
When you set averagingPeriod to anything other than 10 the line graph doesn't work.
[broken line graph.zip](https://github.com/HanSolo/Medusa/files/4306817/broken.line.graph.zip)

**Comment by HanSolo** [comment]
The sparkline skin in Medusa was from the time before I've created TilesFX (my other library for creating dashboards). So if you would like to create a dashboard I recommend using TilesFX which has much more features for dashboards than Medusa. You can combine both libraries and use Medusa in TilesFX which often makes sense. TilesFX also contains a SparkLine skin. To be honest I'm thinking about taking the two tile skins out of this library because the TilesFX library is all about tiles :)

**Comment by HanSolo** [comment]
Fixed with latest commit
