### ISSUE TITLE
Line graph pushes loads of zeros to datavalues as soon as you start pushing values 

### ISSUE THREAD

**Issue by KingGax** [HanSolo/Medusa#189]
Regardless of what you set min to be as soon as you push the first values it fills with zeros which ruins the zoomed in effect of the graph.
[line min value.zip](https://github.com/HanSolo/Medusa/files/4526137/line.min.value.zip)

**Comment by HanSolo** [comment]
Sorry for the late reply, just stumbled upon your report. So I guess you use the TileSparklineSkin? When I created the skins starting with TileNNNSkin I figured out that it makes more sense to separate them into their own library. So you will find a library called TilesFX that only contains tiles for dashboards. All further development related to tiles went into TilesFX instead of these skins in Medusa. So I suggest you use TilesFX for the sparkline. Nevertheless I will check if it is possible to port the SparkLineTileSkin functionality back to Medusa.
