### ISSUE TITLE
How to set propeties boader for bar

### ISSUE THREAD

**Issue by PAIDI-RAMESH** [HanSolo/Medusa#195]
![image](https://user-images.githubusercontent.com/61821550/88071978-1f5be000-cb92-11ea-9dba-ebc1e39c1615.png)
![image](https://user-images.githubusercontent.com/61821550/88072236-6cd84d00-cb92-11ea-927b-8a990984c356.png)

**Comment by HanSolo** [comment]
Because of the missing description I guess you would like to know how to set the border for the bar???
There is no property in the Gauge class to set the border of the bar directly, instead you can create your own skin and design it as you like.
The easiest way would be to take the LinearSkin and create a copy of it e.g. MyLinearSkin. In this skin you can modify the code however you like it and if you are done with your modifications you can use your skin as follows.
```java
Gauge gauge = GaugeBuilder.create()
                          .skinType(SkinType.GAUGE)
                          .prefSize(100, 300)
                          .build();
gauge.setSkin(new MyLinearSkin(gauge));
```
