### ISSUE TITLE
Best way to have clock and gauge same height?

### ISSUE THREAD

**Issue by wimdeblauwe** [HanSolo/Medusa#46]
I am trying to make a clock and a gauge using both the LCD skin the same height. I am putting them both in the "top" of a BorderPane. Inside this "top", I have another BorderPane where I place the actual components "left" and "right". This is the result:

![image](https://cloud.githubusercontent.com/assets/1115823/21043293/774a5542-bdf6-11e6-9842-4823f28b6dc5.png)

On both, I have called:

```
.maxSize(200, 85)
.prefHeight(85)
```

You can see that the gauge on the left has some padding on top, which is not present on the clock on the right. The clock also has some right padding.

You can also see that they are different height.

It would be great if you could suggest how to make their heights the same.

On a related note: how do I change the temperature gauge to only use up to 3 numbers before the decimal separator (In my case, temparture will not go above 999 degrees C)?

**Comment by wimdeblauwe** [comment]
I have changed the code to use HBox instead, but the problem remains. If I add some debugging background color, then I notice that if I set a maxHeight on the HBox and no sizing on the clock and gauge, I get this effect:

![image](https://cloud.githubusercontent.com/assets/1115823/21046657/f8bf5d3e-be05-11e6-9ed7-2eabb04592b5.png)

So I just need a way for the clock and the gauge to draw to the left or the right of his background instead of the center. Is this possible in Medusa ?

**Comment by HanSolo** [comment]
The problem was related to the different default size of both components which leads to different aspect ratios which then leads to different calculations of size. 
In release 6.9 I adjusted both components to the same default size so that it should be easier to make them both the same size. Nevertheless I have to make the LcdSkin better resizable in width...but that will be a in future release. I will release 6.9 today so it should appear on Maven Central at some point today :)

**Comment by wimdeblauwe** [comment]
Thx!

Will this also allow me to have the gauge against the left edge and the clock against the right edge (See 2nd screenshot)?
